servers:
  - name: receiver
    management_ip: 192.168.65.4
    ports:
      - id: 0
        ip: 192.168.65.5
        default_gateway: 192.168.65.1

  - name: transmitter
    management_ip: 192.168.65.5
    ports:
      - id: 1
        ip: 192.168.65.4
        default_gateway: 192.168.65.1

tests:
  - name: 2_servers_latency_test
    duration: 10
    transmit:
      - from: transmitter:1
        to: receiver:0
        profile_file: examples/profiles/latency_profile.py
 #       tunables:
  #        pps: 100
   #       flow_stats: latency
    #      flow_stats_pps: 100
     #     flow_stats_pg_id: 11
