servers:
  - name: trex_server
    management_ip: 127.0.0.1
    ports:
      - id: 0
        ip: 192.168.65.4
        default_gateway: 192.168.65.1
        service_mode: true
        attributes:
          promiscuous: true
      - id: 1
        ip: 192.168.65.5
        default_gateway: 192.168.65.1
        service_mode: true
        attributes:
          promiscuous: true

tests:
  - name: loopback_test
    duration: 10
    transmit:
      - from: trex_server:0
        to: trex_server:1
        profile_file: examples/profiles/latency_profile.py
        tunables:
          pps: 100000
