servers:
  - name: transmitter
    management_ip: 192.168.70.2
    ports:
      - id: 0
        ip: 192.168.70.3
        default_gateway: 192.168.70.1

  - name: receiver
    management_ip: 192.168.70.3
    ports:
      - id: 1
        ip: 192.168.70.2
        default_gateway: 192.168.70.1

tests:
  - name: loopback_test
    duration: 5
    transmit:
      - from: transmitter:0
        to: receiver:1
        profile_file: examples/profiles/latency_profile.py
#        tunables:
#          pps: 10000
#          flow_stats: stats
#          flow_stats_pg_id: 10
